// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0BW5LgZyhxPQ2ifgfDXwgtmy485eR4M0',
    appId: '1:991471677738:web:9eb5bc33339ad1e05dee53',
    messagingSenderId: '991471677738',
    projectId: 'yellowflowers-58d52',
    authDomain: 'yellowflowers-58d52.firebaseapp.com',
    databaseURL: 'https://yellowflowers-58d52-default-rtdb.firebaseio.com',
    storageBucket: 'yellowflowers-58d52.appspot.com',
    measurementId: 'G-P5VHBV07VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCfR7Rc4iDP8RuBrDw0ZMVwUxrmcdukV4',
    appId: '1:991471677738:android:9f3a4eb84a7f23735dee53',
    messagingSenderId: '991471677738',
    projectId: 'yellowflowers-58d52',
    databaseURL: 'https://yellowflowers-58d52-default-rtdb.firebaseio.com',
    storageBucket: 'yellowflowers-58d52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAPfsXRe-5EVvCVunvyDfAZKwNklj5yX0',
    appId: '1:991471677738:ios:a3c0552d8d4bdb375dee53',
    messagingSenderId: '991471677738',
    projectId: 'yellowflowers-58d52',
    databaseURL: 'https://yellowflowers-58d52-default-rtdb.firebaseio.com',
    storageBucket: 'yellowflowers-58d52.appspot.com',
    iosBundleId: 'com.jorgegrullon.yellowFlowers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAPfsXRe-5EVvCVunvyDfAZKwNklj5yX0',
    appId: '1:991471677738:ios:a3c0552d8d4bdb375dee53',
    messagingSenderId: '991471677738',
    projectId: 'yellowflowers-58d52',
    databaseURL: 'https://yellowflowers-58d52-default-rtdb.firebaseio.com',
    storageBucket: 'yellowflowers-58d52.appspot.com',
    iosBundleId: 'com.jorgegrullon.yellowFlowers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0BW5LgZyhxPQ2ifgfDXwgtmy485eR4M0',
    appId: '1:991471677738:web:e0ebf42df5bbe9095dee53',
    messagingSenderId: '991471677738',
    projectId: 'yellowflowers-58d52',
    authDomain: 'yellowflowers-58d52.firebaseapp.com',
    databaseURL: 'https://yellowflowers-58d52-default-rtdb.firebaseio.com',
    storageBucket: 'yellowflowers-58d52.appspot.com',
    measurementId: 'G-MNH3PE6N10',
  );
}
